// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yygbfhwipvscjtbnyitk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5Z2JmaHdpcHZzY2p0Ym55aXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTc4NTEsImV4cCI6MjA2ODI3Mzg1MX0.e42LbN8PXKYXdJL8BbJDfcvmhKEaP1DAstCecVyIVeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});